# Generated by Django 2.1.1 on 2018-09-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
